#!/usr/bin/env python
from killerbee import *

def show_dev():
    kb = KillerBee()
    print "Dev\tProduct String\tSerial Number"
    for dev in kb.dev_list():
        print "%s\t%s\t%s" % (dev[0], dev[1], dev[2])

if __name__ == '__main__':
    show_dev()
