#! /usr/bin/env python

#  zbtestcrypt - test encryption by decrypting and re-encrypting
# 
#  Adam Laurie <adam@aperturelabs.com>
#  http://www.aperturelabs.com
# 

import sys
import argparse

from scapy.all import *
from killerbee import *
from killerbee.scapy_extensions import *

# APS security mask
APS_SECURITY = 0x02

# encrypt/decrypt packet with appropriate key
def crypt(packet, data= None, encrypt= False):
    global link_key
    global nwk_key

    if packet[ZigbeeSecurityHeader].key_type == 0:
        if link_key == None:
            return False, 'FAILED: No LINK_KEY provided'
        key= link_key
    elif packet[ZigbeeSecurityHeader].key_type == 1:
        if nwk_key == None:
            return False, 'FAILED: No NWK_KEY provided'
        key= nwk_key
    else:
        return False, 'Unknown KEY type'

    if encrypt:
        return True, kbencrypt(packet, data, key, verbose= args.verbose)
    else:
        return True, kbdecrypt(packet, key, verbose= args.verbose)

if __name__ == '__main__':
    # Command-line arguments
    parser = argparse.ArgumentParser(description="zbtestcrypt: \
        Decrypt, re-encrypt and optionally transmit packets for testing and tool development.")
    parser.add_argument('-b', '--begin', action='store', type=int, dest='begin', default=0,
        help='begin processing at packet #')
    parser.add_argument('-c', '--channel', action='store', type=int, default=11,
        help='tx/rx on given channel (default 11)')
    parser.add_argument('-D', action='store_true', dest='showdev',
        help='list KillerBee devices')
    parser.add_argument('-e', '--end', action='store', type=int, dest='end', default=0,
        help='end processing at packet #')
    parser.add_argument('-i', '--interface', action='store', type=str, default=None,
        help='provide the USB ID or Serial Device Path to use that device')
    parser.add_argument('-k', '--network_key', action='store', type=str, default=None,
        help='provide the NWK_KEY in HEX')
    parser.add_argument('-l', '--link_key', action='store', type=str, default=None,
        help='provide the LINK_KEY in HEX')
    parser.add_argument('-r', '--pcapfile', action='store', default=None,
        help='pcap file to test')
    parser.add_argument('-R', '--dsnafile', action='store', default=None,
        help='Daintree SNA file to test')
    parser.add_argument('-s', '--sleep', action='store', type=float, default=1.0,
        help='if tx, wait given seconds between packet injections (default 1.0)')
    parser.add_argument('-T', '--transmit_original', action='store_true', dest='transmit_original',
        help='transmit original packets for independant capture/analysis')
    parser.add_argument('-t', '--transmit_crypted', action='store_true', dest='transmit_crypted',
        help='transmit re-encrypted packets for independant capture/analysis')
    parser.add_argument('-v', '--verbose', action='store', type=int, default=0,
        help='set debug verbosity')
    args = parser.parse_args()

    if args.showdev:
        show_dev()
        exit(False)

    if args.pcapfile == None and args.dsnafile == None:
        print >>sys.stderr, "ERROR: Must specify a capture file using -r (libpcap) or -R (Daintree SNA)"
        exit(True)

    if args.pcapfile != None and args.dsnafile != None:
        print >>sys.stderr, "ERROR: Must specify only one of -r (libpcap) or -R (Daintree SNA)"
        exit(True)

    if args.network_key and len(args.network_key) != 32:
        print >>sys.stderr, "ERROR: Must specify 16 byte NWK_KEY in HEX"
        exit(True)
    if args.network_key:
        try:
            nwk_key= args.network_key.decode('hex')
        except:
            print >>sys.stderr, "ERROR: Invalid NWK_KEY"
            exit(True)

    if args.link_key and len(args.link_key) != 32:
        print >>sys.stderr, "ERROR: Must specify 16 byte LINK_KEY in HEX"
        exit(True)
    if args.link_key:
        try:
            link_key= args.link_key.decode('hex')
        except:
            print >>sys.stderr, "ERROR: Invalid LINK_KEY"
            exit(True)
    else:
        link_key= None

    if args.pcapfile is not None:
        data= kbrdpcap(args.pcapfile)

    if args.dsnafile is not None:
        data= kbrddain(args.dsnafile)

    print
    print '%d packets read' % len(data)

    count= 0
    testcount= 0
    failed= 0
    passed= 0
    aps_failed= 0
    aps_passed= 0

    for packet in data:
        count += 1
        print
        if args.begin and count < args.begin:
            continue
        if args.end and count > args.end:
            break
        print 'Packet:', count
        print '  ', packet.summary()
        if args.verbose:
            print '  ', repr(packet)

        # ignore frames with no encrypted payload
        if not packet.haslayer(ZigbeeNWK) or not packet.haslayer(ZigbeeSecurityHeader):
            print '    no payload - skipping!'
            continue

        if packet.haslayer(ZigbeeSecurityHeader):
            print '   decrypting NWK...'
            stat, decrypted = crypt(packet)
            if stat:
                print '     ', decrypted.summary()
                if args.verbose:
                    print '     ', repr(decrypted)
                if args.verbose > 1:
                    print ' HEX:', str(decrypted).encode('hex')
            else:
                print '     ', decrypted

            # If we have an APS layer and it's encrypted, build new packet with ZigbeeNWK so we can decrypt it
            if decrypted.haslayer(ZigbeeAppDataPayload) and decrypted[ZigbeeAppDataPayload].frame_control & APS_SECURITY:
                tmppkt = copy.copy(packet)
                tmppkt[ZigbeeNWK].remove_payload()
                tmppkt /= decrypted[ZigbeeAppDataPayload]
                print '      decrypting APS...'
                if args.verbose:
                    print '        ', repr(tmppkt)
                if args.verbose > 1:
                    print ' HEX:', str(tmppkt).encode('hex')
                stat, app_decrypt= crypt(tmppkt)
                if stat:
                    aps_passed += 1
                    print '        ', app_decrypt.summary()
                    if args.verbose:
                        print '        ', repr(app_decrypt)
                    if args.verbose > 1:
                        print ' HEX:', str(app_decrypt).encode('hex')
                else:
                    aps_failed += 1
                    print '        ', app_decrypt

                print '      encrypting APS...'
                tmppkt = copy.copy(packet)
                tmppkt[ZigbeeNWK].remove_payload()
                tmppkt /= decrypted[ZigbeeAppDataPayload]
                if args.verbose:
                    print '          ', repr(tmppkt)
                stat, recrypt = crypt(tmppkt, data= app_decrypt, encrypt= True)
                if stat:
                    decrypted.data= recrypt.data
                    decrypted.mic= recrypt.mic
                    if args.verbose:
                        print '          ', repr(decrypted)
                else:
                    print '          ', recrypt

            print '   encrypting NWK...'
            stat, newpkt= crypt(packet, data= decrypted, encrypt= True)
            if stat:
                if args.verbose:
                    print '  ', repr(newpkt)
            else:
                print '     ', newpkt
            if newpkt == packet:
                print '   Packet match: OK'
                passed += 1
            else:
                print '   Packet match: FAILED!'
                failed += 1

        if args.transmit_original:
            print '      transmitting ORIGINAL on channel', args.channel
            try:
                kbsendp(packet, channel=args.channel, inter=args.sleep)
                print '        OK'
            except:
                print '        FAILED!'
        if args.transmit_crypted:
            print '      transmitting RE-ENCRYPTED on channel', args.channel
            try:
                kbsendp(newpkt, channel=args.channel, inter=args.sleep)
                print '        OK'
            except:
                print '        FAILED!'
        testcount += 1

    print
    print '%d of %d packets tested' % (testcount, len(data))
    print '  NWK crypto passed:', passed
    print '  NWK crypto failed:', failed
    print '    APS crypto passed:', aps_passed
    print '    APS crypto failed:', aps_failed
    exit(False)
