#!/usr/bin/env python

'''
Print a list of the attached KillerBee recognized devices to stdout.

The -g flag may be provided to ignore a serial device, such as an attached GPS
serial device which should be ignored by KillerBee.
'''

import sys
from killerbee import show_dev

arg_gpsdev = None

if __name__ == '__main__':
    while len(sys.argv) > 1:
        op = sys.argv.pop(1)
        if op == '-g':
            arg_gpsdev = sys.argv.pop(1)
    show_dev(gps=arg_gpsdev)

