#! /usr/bin/env python

__version__ = '0.5'
import logging
log_killerbee = logging.getLogger('scapy.killerbee')

try:
	from scapy.all import *
except ImportError:
	print 'This Requires Scapy To Be Installed.'
	from sys import exit
	exit(-1)

from killerbee import *
from killerbee.scapy_extensions import *	# this is explicit because I didn't want to modify __init__.py

del hexdump
from scapy.utils import hexdump				# Force using Scapy's hexdump()
import os

if os.getuid():
	log_killerbee.warning("Most KillerBee functionality requires root privileges.")

if __name__ == '__main__':
	interact(mydict = globals(), mybanner = 'KillerBee Extension v' + __version__)
