#!/usr/bin/env python

'''
Sends sniffed IEEE 802.15.4 packets to Wireshark via a named pipe.
(ryan@riverloopsecurity.com)
'''

import sys
import os
import argparse
import subprocess

from killerbee import *


def main():

    # Command-line arguments
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('-i', '--iface', '--dev', action='store', dest='devstring')
    #parser.add_argument('-g', '--gps', '--ignore', action='append', dest='ignore')
    parser.add_argument('-p', '--ppi', action='store_true')
    parser.add_argument('-c', '-f', '--channel', action='store', type=int, default=None)
    parser.add_argument('-n', '--count', action='store', default=None)
    parser.add_argument('-D', action='store_true', dest='showdev')
    args = parser.parse_args()

    if args.showdev:
        show_dev()
        sys.exit(0)

    # Start KillerBee
    with KillerBee(device=args.devstring) as kb:
        try:
            kb.set_channel(args.channel)
        except ValueError as e:
            print 'ERROR:', e
            sys.exit(1)

        kb.sniffer_on()

        # Start Wireshark
        wireshark_proc = subprocess.Popen(
                ['wireshark','-k','-i','-'],    # Read packets from stdin immediately
                stdin = subprocess.PIPE,
                stderr = open(os.devnull, 'w'),
                preexec_fn = os.setpgrp,        # Own process group; stay open after we exit
                )

        # Create a PCAP dumper to write packets to wireshark
        with PcapDumper(DLT_IEEE802_15_4, wireshark_proc.stdin, ppi=args.ppi) as pd:

            rf_freq_mhz = (args.channel - 10) * 5 + 2400
            print("zbwireshark: listening on \'{0}\'".format(kb.get_dev_info()[0]))

            try:
                packetcount = 0
                while args.count != packetcount:
                    # Wait for the next packet
                    packet = kb.pnext()

                    rc = wireshark_proc.poll()
                    if rc is not None:
                        print("Wireshark exited ({0})".format(rc))
                        break

                    if packet != None:
                        packetcount+=1
                        pd.pcap_dump(packet['bytes'], ant_dbm=packet['dbm'], freq_mhz=rf_freq_mhz)

            except KeyboardInterrupt:
                pass
            except IOError as e:
                if e.errno == 32:
                    #print("ERROR: Pipe broken. Was Wireshark closed or stopped?")
                    pass
                else:
                    raise

            print("{0} packets captured".format(packetcount))

if __name__ == '__main__':
    main()
